import { Inter } from "@/src/utils/fonts";
import type { Metadata, Viewport } from "next";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by Ruslan Batsulia",
  icons: {
    icon: "/images/favicon.ico",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="uk" className={Inter.variable}>
      <body>{children}</body>
    </html>
  );
}
